user www-data;
worker_processes auto;
pcre_jit on;

pid        logs/nginx.pid;

# 对应编译参数 --with-threads
events {
    worker_connections 1024;
    use epoll;
    multi_accept on;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    # 性能加速 (对应 --with-file-aio)
    sendfile        on;
    tcp_nopush      on;
    aio             threads;
    
    # 保持长连接
    keepalive_timeout 65;
    
    # 引入 conf.d 下的默认配置
    include ./conf.d/*.conf;
}